### ISSUE TITLE
What the difference between `sunriset()` and `crepuscule()` with `solarDep=0`

### ISSUE THREAD

**Issue by Rafnuss** [adokter/suntools#16]
Thanks a lot for the package. 
I was just wandering why is there a difference between these two codes:
```{r}
> suntools::sunriset(
+     crds = matrix(c(0,0), ncol = 2),
+     dateTime = as.POSIXct("2000-01-01 00:00:00 UTC"),
+     direction = "sunset",
+     POSIXct.out = TRUE
+ )
   day_frac                time
1 0.7965567 2000-01-01 19:07:02
> suntools::crepuscule(
+     crds = matrix(c(0,0), ncol = 2),
+     dateTime = as.POSIXct("2000-01-01 00:00:00 UTC"),
+     solarDep = 0,
+     direction = "dusk",
+     POSIXct.out = TRUE
+ )
   day_frac                time
1 0.7940427 2000-01-01 19:03:25
```
Thanks

**Comment by iskandari** [comment]
I think this has to do with the way hour angles are set differently for each function, `sunriset` adds atmospheric refraction and the sun’s radius:

[.hangleCrepuscule ](https://github.com/adokter/suntools/blob/374fff7b2f595fabb8bf75d928c63b6e2f099e98/R/sun.R#L254)
assumes the geometric horizon as 90 degrees plus the solar depression.

[.hangleSunriset](https://github.com/adokter/suntools/blob/374fff7b2f595fabb8bf75d928c63b6e2f099e98/R/sun.R#L275)
adjusts for atmospheric refraction and the sun's radius, which I think is meant to calculate when the upper edge of the sun would appear/disappear from the horizon. So here we begin with 90.833 degrees instead of 90 degrees.

**Comment by Rafnuss** [comment]
Thanks for the explanation @iskandari ! that makes sense, although I still don't fully understand why refraction is only added to sunriset and not crepuscule in the original calculation. I guess the precision is anyway not precise to the minutes.
